#! /bin/bash

SO_LONG=./so_long
MAP_DIR=so_long_leaktester/maps
RED='\033[0;31m'
GREEN='\033[0;32m'
MAGENTA='\033[0;35m'
ENDCOLOR='\033[0m'

rm -f "$MAP_DIR"/*.log
for file in "$MAP_DIR"/*; do
	if [ "$file" == "$MAP_DIR/valid_esc.ber" ]; then
		cat "$MAP_DIR/wrong_extension.txt"
		sleep 2
	elif [ "$file" == "$MAP_DIR/valid_winning.ber" ]; then
		cat "$MAP_DIR/wrong_extension2.txt"
		sleep 2
	elif [ "$file" == "$MAP_DIR/valid_cross.ber" ]; then
		cat "$MAP_DIR/wrong_extension.be"
		sleep 2
	fi
	valgrind --leak-check=full --show-reachable=yes --show-leak-kinds=all --error-limit=no --gen-suppressions=all --log-file="$file.log" $SO_LONG $file > /dev/null 2>&1
	bytes=$(cat "$file.log" | awk '/in use at exit/ {print $6}')
	if [[ $bytes -eq 0 ]]; then
		echo -e "$GREEN""No leaks in $file $ENDCOLOR"
	else
		echo -e "$RED""$bytes bytes leaked in $file $ENDCOLOR"
	fi
done


echo -e "$MAGENTA""Log files can be found in $MAP_DIR directory$ENDCOLOR"
