#! /bin/bash

SO_LONG=../so_long
MAP_DIR=maps
RED='\033[0;31m'
GREEN='\033[0;32m'
ENDCOLOR='\033[0m'

rm -f "$MAP_DIR"/*.log
for file in "$MAP_DIR"/*; do
	valgrind --leak-check=full --show-reachable=yes --show-leak-kinds=all --error-limit=no --gen-suppressions=all --log-file="$file.log" $SO_LONG $file 2> /dev/null
	bytes=$(cat "$file.log" | awk '/in use at exit/ {print $6}')
	if [[ $bytes -eq 0 ]]; then
		echo -e "$GREEN No leaks in $file $ENDCOLOR"
	else
		echo -e "$RED $bytes bytes leaked in $file $ENDCOLOR"
	fi
done


echo -e "$GREEN Log files generate in $MAP_DIR directory$ENDCOLOR"
